# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:10

stages:
  - test
  - deploy

test:inventory:
  stage: test
  script:
    - npm install gulp-cli -g
    - npm install
    - gulp
  except:
    - master

test:doc:
  stage: test
  script:
    - cd docusaurus
    - npm install
    - npm run build
  except:
    - master

pages:
  stage: deploy
  script:
    - npm install gulp-cli -g
    - npm install # inventory dependencies
    - gulp
    - mkdir public
    - cp -rT build/ public/ # copying the inventory
    - cd docusaurus
    - npm install # documentation dependencies
    - cp -rT build/ ../public # copying the documentation
  artifacts:
    paths:
      - public
  only:
    - master
