# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:6

stages:
  - test
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install gulp-cli -g
  - npm install

test:
  stage: test
  script:
    - gulp
  except:
    - master

pages:
  stage: deploy
  script:
    - gulp
    - mkdir public
    - mv build/* public/
  artifacts:
    paths:
      - public
  only:
    - master

